application: oaklandmunicipalband
version: 1
runtime: python27
api_version: 1
threadsafe: true

#handlers:
#- url: /
#  static_dir: website

handlers:
- url: /
  static_files: website/index.html
  upload: website/index.html

- url: /(.+)
  static_files: website/\1
  upload: website/(.+)
